import type { ReviewStep } from "@/types/review";
export const reviewSteps: ReviewStep[] = [
  { id:"messages", title:"Messages", decisionQuestion:"Have I left anyone waiting?", objective:"Review your last 20 iMessages and SMS conversations.", prompts:["Look for promises made.","Look for unanswered questions.","Capture replies, decisions, arrangements, and loose ends."] },
  { id:"whatsapp", title:"WhatsApp", decisionQuestion:"Is there any conversation I need to continue?", objective:"Review your last 20 WhatsApp conversations.", prompts:["Check family, friends, clients, prospects, and practical matters.","Capture any action, reply, or follow-up.","Notice any relationship that needs attention."] },
  { id:"voicemail", title:"Voicemail", decisionQuestion:"Is my voicemail clear?", objective:"Review and delete all voicemails.", prompts:["Open the Phone app.","Capture any action before deleting.","Delete all voicemails once reviewed."] },
  { id:"completed-reminders", title:"Completed Reminders", decisionQuestion:"Have I cleared completed items?", objective:"Delete completed reminders.", prompts:["Open Reminders.","Delete completed items.","Capture any completed item that creates a further action."] },
  { id:"reminder-lists", title:"Reminder Lists", decisionQuestion:"Are my reminder categories still relevant?", objective:"Review each reminder category for ongoing relevance.", prompts:["Remove stale or duplicate reminders.","Add due dates where needed.","Keep, rename, merge, or delete lists where appropriate."] },
  { id:"past-seven-days", title:"Previous 7 Days", decisionQuestion:"What did the last week create?", objective:"Review each of the last seven days for open loops.", prompts:["Look for promises, invoices, receipts, expenses, and follow-ups.","Check meetings, calls, lunches, family events, and travel.","Capture anything still unfinished."] },
  { id:"next-twenty-one-days", title:"Next 21 Days", decisionQuestion:"What requires preparation?", objective:"Review each of the next 21 days.", prompts:["Look for conflicts, travel, reading, documents, and preparation needs.","Create reminders or preparation blocks.","Identify anything that could become a surprise."] },
  { id:"email", title:"Email", decisionQuestion:"Which emails require a decision?", objective:"Review email for actions, replies, and waiting-for items.", prompts:["Review unread, flagged, and waiting-for emails.","Archive or delete noise.","Capture decisions, replies, and delegated actions."] },
  { id:"crm", title:"CRM", decisionQuestion:"Who needs to hear from me?", objective:"Review business development and client follow-ups.", prompts:["Check prospects, proposals, invoices, and stalled opportunities.","Identify the next action for each live opportunity.","Capture chase, close, schedule, or nurture actions."] },
  { id:"linkedin", title:"LinkedIn", decisionQuestion:"Which relationships need attention?", objective:"Review LinkedIn engagement and business opportunities.", prompts:["Check messages, comments, invitations, and post engagement.","Capture people to reply to, thank, or follow up.","Identify warm leads or useful relationship actions."] },
  { id:"weekly-priorities", title:"Weekly Priorities", decisionQuestion:"If I only achieved three things next week, what should they be?", objective:"Choose your Big Three for the coming week.", prompts:["Choose no more than three priorities.","Make each priority specific enough to act on.","Include personal, family, or health commitments where they matter."] },
  { id:"positive-close", title:"Positive Close", decisionQuestion:"What should I recognise before I move on?", objective:"End the review with progress and perspective.", prompts:["What was my biggest win this week?","Who deserves thanks or recognition from me next week?","What am I looking forward to?"] }
];
